#include "portinit.h"


void PortA_init (void)
{
	SYSCTL_RCGCGPIO_R |= 0x01;
	GPIO_PORTA_DIR_R |= 0x3C ;
	GPIO_PORTA_AFSEL_R = 0;
	GPIO_PORTA_PCTL_R = 0;
	GPIO_PORTA_AMSEL_R =0;
	GPIO_PORTA_DEN_R |= 0xFC;
	GPIO_PORTA_LOCK_R = 0x4C4F434B;
	GPIO_PORTA_CR_R |= 0xFC;
}

void PortC_init (void)
{
	SYSCTL_RCGCGPIO_R |= 0x04;
	GPIO_PORTC_DIR_R |= 0xF0;
	GPIO_PORTC_AFSEL_R = 0;
	GPIO_PORTC_PCTL_R = 0;
	GPIO_PORTC_AMSEL_R =0;
	GPIO_PORTC_DEN_R |= 0xF0;
	GPIO_PORTC_LOCK_R = 0x4C4F434B;
	GPIO_PORTC_CR_R |= 0xF0;
}

void PortF_init (void)
{
	SYSCTL_RCGCGPIO_R |= 0x20;
	GPIO_PORTF_DIR_R &= ~0x10;
	GPIO_PORTF_AFSEL_R = 0;
	GPIO_PORTF_PCTL_R = 0;
	GPIO_PORTF_AMSEL_R =0;
	GPIO_PORTF_DEN_R |= 0x10;
	GPIO_PORTF_LOCK_R = 0x4C4F434B;
	GPIO_PORTF_CR_R |= 0x10;
	GPIO_PORTF_PUR_R |= 0x10;
}